services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /PATH_TO_YOUR_CONFIG:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    ports:
      - "8123:8123"        # Si tu app Flask expone el puerto 5000
      
  esphome:
    container_name: esphome
    image: esphome/esphome:latest
    volumes:
      - /ruta/a/tu/configuracion/esphome:/config
      - /etc/localtime:/etc/localtime:ro
      - /dev/ttyUSB0:/dev/ttyUSB0 # Opcional: para flashear por USB
    restart: unless-stopped
    ports:
      - "6052:6052"